In [128]:
%load_ext nb_black

The nb_black extension is already loaded. To reload it, use:
  %reload_ext nb_black


<IPython.core.display.Javascript object>

In [129]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import warnings

warnings.filterwarnings("ignore")
# from sklearn.metrics import recall_score, precision_score

<IPython.core.display.Javascript object>

In [130]:
df1 = pd.read_csv("IRIS.csv")

<IPython.core.display.Javascript object>

In [131]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

<IPython.core.display.Javascript object>

In [132]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


<IPython.core.display.Javascript object>

In [6]:
# import random

# random.seed(10)
# r_indexes2 = random.sample(df1.index.values.tolist(), k=10)
# r_indexes2

<IPython.core.display.Javascript object>

In [7]:
# df2 = df1.copy()

<IPython.core.display.Javascript object>

In [8]:
# df2 = df2.iloc[r_indexes2, :]
# df2

<IPython.core.display.Javascript object>

In [9]:
# df3 = df2.copy()
# df4 = df2.copy()
# df5 = df2.copy()

<IPython.core.display.Javascript object>

In [10]:
# df3["Iris-setosa"] = df3["species"] == "Iris-setosa"
# df4["Iris-versicolor"] = df4["species"] == "Iris-versicolor"
# df5["Iris-virginica"] = df5["species"] == "Iris-virginica"

<IPython.core.display.Javascript object>

In [11]:
# df3.drop("species", axis=1, inplace=True)
# df4.drop("species", axis=1, inplace=True)
# df5.drop("species", axis=1, inplace=True)

<IPython.core.display.Javascript object>

In [12]:
# df3["Iris-setosa"].replace({True: 1, False: 0}, inplace=True)
# df4["Iris-versicolor"].replace({True: 1, False: 0}, inplace=True)
# df5["Iris-virginica"].replace({True: 1, False: 0}, inplace=True)

<IPython.core.display.Javascript object>

In [13]:
# df3

<IPython.core.display.Javascript object>

In [14]:
# df4

<IPython.core.display.Javascript object>

In [15]:
# df5

<IPython.core.display.Javascript object>

In [133]:
X = df1.drop("species", axis=1)

<IPython.core.display.Javascript object>

In [134]:
y = df1["species"]

<IPython.core.display.Javascript object>

In [135]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

<IPython.core.display.Javascript object>

In [136]:
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


<IPython.core.display.Javascript object>

# OVR

In [137]:
binary_clf = LogisticRegression(multi_class="ovr")

<IPython.core.display.Javascript object>

In [138]:
binary_clf.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

<IPython.core.display.Javascript object>

In [139]:
binary_clf.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

<IPython.core.display.Javascript object>

In [140]:
binary_clf.coef_

array([[-0.4657307 ,  0.75557672, -2.18424884, -0.89086938],
       [ 0.09008285, -2.15936938,  0.43131505, -0.89044443],
       [-0.44078719, -0.05267536,  2.52122839,  2.04878938]])

<IPython.core.display.Javascript object>

In [141]:
binary_clf.intercept_

array([  6.85749195,   4.47328608, -12.6534482 ])

<IPython.core.display.Javascript object>

In [142]:
X_test.loc[75, :]

sepal_length    6.6
sepal_width     3.0
petal_length    4.4
petal_width     1.4
Name: 75, dtype: float64

<IPython.core.display.Javascript object>

In [143]:
def sig(x):
    return 1 / (1 + np.e ** (-x))

<IPython.core.display.Javascript object>

In [144]:
score = pd.DataFrame(
    {
        "clf1_coef_s": binary_clf.coef_[0],
        "clf2_coef_s": binary_clf.coef_[1],
        "clf3_coef_s": binary_clf.coef_[2],
        "x": X_test.loc[75, :].values,
    }
)
score["clf1_m.x"] = score["clf1_coef_s"] * score["x"]
score["clf2_m.x"] = score["clf2_coef_s"] * score["x"]
score["clf3_m.x"] = score["clf3_coef_s"] * score["x"]
score

clf1_coef_s  clf2_coef_s  clf3_coef_s    x  clf1_m.x  clf2_m.x   clf3_m.x
0    -0.465731     0.090083    -0.440787  6.6 -3.073823  0.594547  -2.909195
1     0.755577    -2.159369    -0.052675  3.0  2.266730 -6.478108  -0.158026
2    -2.184249     0.431315     2.521228  4.4 -9.610695  1.897786  11.093405
3    -0.890869    -0.890444     2.048789  1.4 -1.247217 -1.246622   2.868305

<IPython.core.display.Javascript object>

In [145]:
clf_1_score = score["clf1_m.x"].sum() + binary_clf.intercept_[0]
clf_2_score = score["clf2_m.x"].sum() + binary_clf.intercept_[1]
clf_3_score = score["clf3_m.x"].sum() + binary_clf.intercept_[2]

<IPython.core.display.Javascript object>

In [146]:
print(clf_1_score)
print(clf_2_score)
print(clf_3_score)

-4.8075125094751465
-0.7591112400875604
-1.758959701921821


<IPython.core.display.Javascript object>

In [147]:
binary_clf.decision_function([X_test.loc[75, :]])

array([[-4.80751251, -0.75911124, -1.7589597 ]])

<IPython.core.display.Javascript object>

In [148]:
clf_1_p = sig(clf_1_score)
clf_2_p = sig(clf_2_score)
clf_3_p = sig(clf_3_score)

<IPython.core.display.Javascript object>

In [149]:
print(clf_1_p)
print(clf_2_p)
print(clf_3_p)

0.008101974485906195
0.31883925670071744
0.14692067766697367


<IPython.core.display.Javascript object>

In [150]:
binary_clf.predict_proba([X_test.loc[75, :]])

array([[0.01709775, 0.67285268, 0.31004956]])

<IPython.core.display.Javascript object>

In [151]:
s1 = clf_1_p + clf_2_p + clf_3_p
s1

0.47386190885359736

<IPython.core.display.Javascript object>

In [152]:
print(clf_1_p / s1)
print(clf_2_p / s1)
print(clf_3_p / s1)

0.017097754291977393
0.6728526829094104
0.3100495627986122


<IPython.core.display.Javascript object>

In [153]:
binary_clf.predict([X_test.loc[75, :]])

array(['Iris-versicolor'], dtype=object)

<IPython.core.display.Javascript object>

In [154]:
y_test.loc[75]

'Iris-versicolor'

<IPython.core.display.Javascript object>

# Softmax Regression

In [157]:
multinomial = LogisticRegression(multi_class="multinomial")
multinomial.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

<IPython.core.display.Javascript object>

In [158]:
multinomial.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

<IPython.core.display.Javascript object>

In [159]:
multinomial.coef_

array([[-0.4335725 ,  0.75086106, -2.24668818, -0.93769057],
       [ 0.58137761, -0.53166916, -0.12925446, -0.79357991],
       [-0.14780511, -0.21919189,  2.37594264,  1.73127049]])

<IPython.core.display.Javascript object>

In [54]:
multinomial.intercept_

array([  9.22058011,   1.7000228 , -10.92060291])

<IPython.core.display.Javascript object>

In [55]:
X_test

sepal_length  sepal_width  petal_length  petal_width
14            5.8          4.0           1.2          0.2
98            5.1          2.5           3.0          1.1
75            6.6          3.0           4.4          1.4
16            5.4          3.9           1.3          0.4
131           7.9          3.8           6.4          2.0
56            6.3          3.3           4.7          1.6
141           6.9          3.1           5.1          2.3
44            5.1          3.8           1.9          0.4
29            4.7          3.2           1.6          0.2
120           6.9          3.2           5.7          2.3
94            5.6          2.7           4.2          1.3
5             5.4          3.9           1.7          0.4
102           7.1          3.0           5.9          2.1
51            6.4          3.2           4.5          1.5
78            6.0          2.9           4.5          1.5
42            4.4          3.2           1.3          0.2
92            5.8          2.6           4.0          1.2
66            5.6          3.0           4.5          1.5
31            5.4          3.4           1.5          0.4
35            5.0          3.2           1.2          0.2
90            5.5          2.6           4.4          1.2
84            5.4          3.0           4.5          1.5
77            6.7          3.0           5.0          1.7
40            5.0          3.5           1.3          0.3
125           7.2          3.2           6.0          1.8
99            5.7          2.8           4.1          1.3
33            5.5          4.2           1.4          0.2
19            5.1          3.8           1.5          0.3
73            6.1          2.8           4.7          1.2
146           6.3          2.5           5.0          1.9
91            6.1          3.0           4.6          1.4
135           7.7          3.0           6.1          2.3
69            5.6          2.5           3.9          1.1
128           6.4          2.8           5.6          2.1
114           5.8          2.8           5.1          2.4
48            5.3          3.7           1.5          0.2
53            5.5          2.3           4.0          1.3
28            5.2          3.4           1.4          0.2
54            6.5          2.8           4.6          1.5
108           6.7          2.5           5.8          1.8
112           6.8          3.0           5.5          2.1
17            5.1          3.5           1.4          0.3
119           6.0          2.2           5.0          1.5
103           6.3          2.9           5.6          1.8
58            6.6          2.9           4.6          1.3

<IPython.core.display.Javascript object>

In [56]:
multinomial.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

<IPython.core.display.Javascript object>

In [160]:
multinomial.predict_proba(X_test)

array([[9.85141590e-01, 1.48583262e-02, 8.35379637e-08],
       [2.75810333e-01, 7.20466549e-01, 3.72311746e-03],
       [6.80349745e-03, 8.68200620e-01, 1.24995882e-01],
       [9.85675714e-01, 1.43240639e-02, 2.22426531e-07],
       [1.55630817e-06, 2.00512596e-02, 9.79947184e-01],
       [4.72891748e-03, 5.88449121e-01, 4.06821962e-01],
       [1.70463973e-04, 1.30046217e-01, 8.69783319e-01],
       [9.58396372e-01, 4.16001246e-02, 3.50303300e-06],
       [9.68860570e-01, 3.11386021e-02, 8.28309660e-07],
       [1.30622067e-05, 3.12274093e-02, 9.68759529e-01],
       [1.98153057e-02, 8.69007546e-01, 1.11177148e-01],
       [9.67212495e-01, 3.27861184e-02, 1.38678026e-06],
       [6.82419170e-06, 3.83290355e-02, 9.61664140e-01],
       [7.59391065e-03, 7.67386874e-01, 2.25019215e-01],
       [7.39153470e-03, 7.31252478e-01, 2.61355988e-01],
       [9.87597436e-01, 1.24023699e-02, 1.93644124e-07],
       [2.35808271e-02, 9.29527473e-01, 4.68916999e-02],
       [1.14143436e-02, 6.61864

<IPython.core.display.Javascript object>

In [161]:
multinomial.predict(X_test)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor'], dtype=object)

<IPython.core.display.Javascript object>

In [162]:
y_test

14         Iris-setosa
98     Iris-versicolor
75     Iris-versicolor
16         Iris-setosa
131     Iris-virginica
56     Iris-versicolor
141     Iris-virginica
44         Iris-setosa
29         Iris-setosa
120     Iris-virginica
94     Iris-versicolor
5          Iris-setosa
102     Iris-virginica
51     Iris-versicolor
78     Iris-versicolor
42         Iris-setosa
92     Iris-versicolor
66     Iris-versicolor
31         Iris-setosa
35         Iris-setosa
90     Iris-versicolor
84     Iris-versicolor
77     Iris-versicolor
40         Iris-setosa
125     Iris-virginica
99     Iris-versicolor
33         Iris-setosa
19         Iris-setosa
73     Iris-versicolor
146     Iris-virginica
91     Iris-versicolor
135     Iris-virginica
69     Iris-versicolor
128     Iris-virginica
114     Iris-virginica
48         Iris-setosa
53     Iris-versicolor
28         Iris-setosa
54     Iris-versicolor
108     Iris-virginica
112     Iris-virginica
17         Iris-setosa
119     Iris-virginica
103     Iri

<IPython.core.display.Javascript object>